repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: trailing-whitespace
- repo: https://github.com/myint/autoflake
  rev: v2.3.0
  hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.0
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
        - --max-doc-length=120
        - --ignore=E203,W503,W504
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
