stack_overflow:
    page_size: 15
    num_questions: 5
    num_answers: 5
question: "flatten python list of lists"
summarization_pipeline:
    _target_: tldrai.modules.generation_pipeline.constructed_pipeline.ConstructedPipeline
    model_path: "smallcloudai/Refact-1_6B-fim"
    chat_template: null #${hydra:runtime.cwd}/chat_templates/chat_templates/chatml.jinja
generation_params:
    max_new_tokens: 200
    do_sample: True
    temperature: 0.5
    top_p: 0.95
    use_cache: False
    repetition_penalty: 2.5
prompt: |
    <empty_output>SYSTEM Given a collection of StackOverflow answers related to [{}], please extract the most relevant piece of code.
    "<empty_output>USER {query}\n"
prompt_ending: "<empty_output>ASSISTANT"
is_prompt_codified: False