stack_overflow:
    page_size: 15
    num_questions: 5
    num_answers: 5
question: "flatten python list of lists"
summarization_pipeline:
    _target_: tldrai.modules.generation_pipeline.constructed_pipeline.ConstructedPipeline
    model_path: "Open-Orca/oo-phi-1_5" #"smallcloudai/Refact-1_6B-fim"
    chat_template: ${hydra:runtime.cwd}/chat_templates/chat_templates/chatml.jinja
generation_params:
    max_new_tokens: 200
    do_sample: True
    temperature: 0.5
    top_p: 0.95
    use_cache: True
    repetition_penalty: 2.5
model_token_limit: 2048
prompt: |
    Given a collection of StackOverflow answers related to [{}], please extract the most relevant piece of code.
prompt_ending: |
    
    What's the proper code to {}?
is_prompt_codified: True