stack_overflow:
    page_size: 15
    num_questions: 5
    num_answers: 5
question: "flatten python list of lists"
summarization_pipeline:
    _target_: tldrai.modules.generation_pipeline.constructed_pipeline.ConstructedPipeline
    model_path: "Open-Orca/oo-phi-1_5"
    chat_template: ${hydra:runtime.cwd}/chat_templates/chat_templates/chatml.jinja
generation_params:
    max_new_tokens: 200
    do_sample: True
    temperature: 0.3
    top_p: 0.95
    use_cache: True
    repetition_penalty: 1.5
prompt: |
    Given a collection of StackOverflow answers related to [{}], please summarize the key points by doing the following:

        Identify and extract the most relevant code snippets related to the topic. Focus on those which question title is closest to the topic, have the biggest score and are freshest.
    
        Provide a concise summary for each code snippet you provide. This summary should briefly explain:
            The purpose of the code: What problem does it solve or what functionality does it provide?
            How the code works: A very brief overview of the logic or method used.
            Any important notes or warnings: Include if the code requires specific versions, dependencies, or if there are common pitfalls.
    
        Highlight any variations or alternatives in the code snippets that might be useful for different scenarios or preferences.
    
        Summarize the non-code advice that accompanies the code snippets in a few sentences. Focus on tips, best practices, or explanations that are frequently mentioned or highly valued by the community.

    Please ensure the summary is clear, to the point, and accessible to someone with a basic understanding of the topic.