stack_overflow:
    page_size: 15
    num_questions: 5
    num_answers: 5
no_search: True
question: "apply a function to pandas column"
summarization_pipeline:
    _target_: tldrai.modules.generation_pipeline.constructed_pipeline.ConstructedPipeline
    model_path: "smallcloudai/Refact-1_6B-fim" #"Open-Orca/oo-phi-1_5" #
    chat_template: null #${hydra:runtime.cwd}/chat_templates/chat_templates/chatml.jinja
generation_params:
    max_new_tokens: 300
    attention_mask: True
    do_sample: True
    temperature: 0.01
    top_p: 0.95
    use_cache: True
    repetition_penalty: 5.0
model_token_limit: 4096
history: null
prompt: |
    <empty_output>SYSTEM Please extract the most relevant piece of code related to what the user will ask. Start your answer with code. The non-code answer should be as short as possible.
    <empty_output>USER
prompt_ending: |
    How do I {}?
    <empty_output>ASSISTANT
is_prompt_codified: False
