name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags that follow semantic versioning
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install packages
      run: |
        poetry lock && poetry install --with test

    - name: Install Ollama
      run: |
        curl -sSL https://ollama.com/install.sh | bash

    - name: Test the package
      run: |
        poetry run pytest  # Adjust if you need to run tests differently

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pip install poetry

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish --build --username __token__ --password $PYPI_TOKEN

  release:
    needs: [build, publish]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/*.whl
        asset_name: tldrai-${{ github.event.release.tag_name }}.whl
        asset_content_type: application/zip
