name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry lock && poetry install

      - name: Install Ollama
        run: |
          # Example installation steps, replace with actual steps for your environment
          curl -sSL https://ollama.com/install.sh | bash

      - name: Run tests
        run: |
          poetry run pytest
