name: CI with poetry and PyPi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  poetry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry lock && poetry install --with test

      - name: Install Ollama
        run: |
          curl -sSL https://ollama.com/install.sh | bash

      - name: Run tests
        run: |
          poetry run pytest

  pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Ollama
      run: |
        curl -sSL https://ollama.com/install.sh | bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tldrai  # Install your package from PyPI
        pip install pytest pytest-mock  # Install testing dependencies

    - name: Run tests
      run: |
        pytest
