name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags that follow semantic versioning
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use the appropriate Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Build wheel
      run: |
        poetry install --no-dev
        poetry build
    
    - name: Install testing dependencies
      run: |
        pip install pytest pyinstrument pytest-mock

    - name: Test the package
      run: |
        pip install dist/*.whl
        pytest  # Adjust if you need to run tests differently

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Ensure the same Python version

    - name: Install Poetry
      run: pip install poetry

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  # Set your PyPI token in the repo secrets
      run: |
        poetry publish --build --username __token__ --password $PYPI_TOKEN

  release:
    needs: [build, publish]
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/*.whl
        asset_name: my_package-${{ github.event.release.tag_name }}.whl
        asset_content_type: application/zip
